spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
        listener:
          auto-startup: false

  sqs:
    queues:
      order-queue: order-queue
      order-callback-queue: order-callback-queue
      production-queue: production-queue
      production-callback-queue: production-callback-queue
      payment-queue: payment-queue
      payment-callback-queue: payment-callback-queue