apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-orchestrator-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/ms-orchestrator-irsa #Todo: Ajustar id
