spring:
  application:
    name: ms-orchestrator

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localstack:4566

  sqs:
    queues:
      order-queue: order-queue
      order-callback-queue: order-callback-queue

      sqs:
        queues:
          order-queue: order-queue
          order-callback-queue: order-callback-queue
          production-queue: production-queue
          production-callback-queue: production-callback-queue
          payment-queue: payment-queue
          payment-callback-queue: payment-callback-queue

server:
  port: 8080
