---
name: CI - Dev (Tests + PR to Hom)

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Unit + Integration Tests (Docker Compose)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verificar Docker Compose
        run: docker compose version

      - name: Subir LocalStack
        run: docker compose up -d orchestrator-localstack

      - name: Aguardar LocalStack ficar saudável
        run: |
          echo "Aguardando LocalStack..."
          
          CONTAINER_ID=$(docker compose ps -q orchestrator-localstack)
          
          if [ -z "$CONTAINER_ID" ]; then
            echo "Container do LocalStack não encontrado"
            docker compose ps
            exit 1
          fi
          
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_ID" || true)
            if [ "$STATUS" = "healthy" ]; then
              echo "LocalStack pronto!"
              exit 0
            fi
            sleep 5
          done
          
          echo "LocalStack não ficou saudável a tempo"
          docker logs "$CONTAINER_ID"
          exit 1   

      - name: Rodar testes (unit + integration)
        run: mvn clean verify

      - name: Derrubar containers
        if: always()
        run: docker compose down -v


  pr-hom:
    name: Criar PR para hom
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Criar Pull Request para Hom
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: hom
          branch: dev
          title: 'Merge dev into hom'
          body: |
            PR automática da branch `dev` para `hom`.
          labels: automatic-pr
          commit-message: '[ci] chore: create PR'
          signoff: true
          delete-branch: false
          always-create: true
